### PR TITLE
Fix build failed multiple-value uuid.NewV4() in single-value context

### PR DESCRIPTION
**Pull request by u5surf**
**issue**
uuid.NewV4 in satori/go.uuid has changed return values to multiple-value(uuid, error)
https://godoc.org/github.com/satori/go.uuid#NewV4

so, I fixed returnes single-value using uuid.Must which is helper as backward compatibility.
https://godoc.org/github.com/satori/go.uuid#Must

**testing**
before:
```
$make build
building krontab
GOPATH=/Users/u5surf/go
go build -ldflags "-X github.com/jacobtomlinson/krontab/version.GitCommit=e88f229b1ebbf8e56f60a9e18197e2fa69ac2cdd -X github.com/jacobtomlinson/krontab/version.BuildDate=2019-03-01-09:30:36 -X github.com/jacobtomlinson/krontab/version.Version=v0.1.6-2-ge88f229" -o bin/krontab
# github.com/jacobtomlinson/krontab/crontab
crontab/crontab.go:459:20: multiple-value uuid.NewV4() in single-value context
make: *** [build] Error 2
```

after:
```
$make build
building krontab
GOPATH=/Users/u5surf/go
go build -ldflags "-X github.com/jacobtomlinson/krontab/version.GitCommit=e88f229b1ebbf8e56f60a9e18197e2fa69ac2cdd+CHANGES -X github.com/jacobtomlinson/krontab/version.BuildDate=2019-03-01-09:32:39 -X github.com/jacobtomlinson/krontab/version.Version=v0.1.6-2-ge88f229-dirty" -o bin/krontab
```

### CODE REVIEW

**Comment by u5surf** [comment]
Oh, I misread go.uuid versions, v.1.2.0 was correct. Sorry

**Comment by jacobtomlinson** [comment]
Thanks anyway 🤣

**Comment by jacobtomlinson** [comment]
Out of curiosity how did you find out about the project? I only created it the other day and I'm keen to spread the word.

**Comment by u5surf** [comment]
@jacobtomlinson
I found this website to search help-wanted issue. 
http://github-help-wanted.com/
Initially, I found #14

**Pull request closed without merging**
